theme: jekyll-theme-architect
title: Virzz & Tools List
description: The Cyber Swiss Army Knife for terminal
google_analytics: "G-7DHX89W1T6"
baidu_tongji: e387ae13fe3f3d4681ce225bfa4c3d80
github:
    owner_url: http://github.com/virzz
