theme: jekyll-theme-architect
title: Virzz & Tools List
description: The Cyber Swiss Army Knife for terminal
google_analytics: "G-7DHX89W1T6"
baidu_tongji: 32049f011b6bf86ab909ca90119f4632
github:
    owner_url: http://github.com/virzz
